In [1]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()


In [2]:
print(train_images.shape)
print(train_labels.shape)


(60000, 28, 28)
(60000,)


In [3]:
print((train_images[0]).shape)
print(train_labels[0])

(28, 28)
5


In [4]:
test_images.shape

(10000, 28, 28)

In [5]:
import matplotlib.pyplot as plt
plt.imshow(train_images[0])
plt.show

<function matplotlib.pyplot.show(*args, **kw)>

In [6]:
#print(train_images[0])

In [7]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255
print(train_images[0].shape)

(784,)


In [8]:
from keras.utils import to_categorical
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [9]:
train_labels.shape

(60000, 10)

In [10]:
from keras import models
from keras import layers
model=models.Sequential()
model.add(layers.Dense(512,activation='relu',input_shape=(784,)))
model.add(layers.Dense(10,activation='softmax'))

In [11]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [12]:
model.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5
469/469 [==============================] - 12s 20ms/step - loss: 0.4332 - accuracy: 0.8712
Epoch 2/5
469/469 [==============================] - 10s 21ms/step - loss: 0.1160 - accuracy: 0.9657
Epoch 3/5
469/469 [==============================] - 9s 20ms/step - loss: 0.0667 - accuracy: 0.9809
Epoch 4/5
469/469 [==============================] - 9s 20ms/step - loss: 0.0502 - accuracy: 0.9847 0s - los
Epoch 5/5
469/469 [==============================] - 9s 20ms/step - loss: 0.0358 - accuracy: 0.9893


In [13]:
test_loss,test_acc=model.evaluate(test_images,test_labels)

313/313 [==============================] - 2s 5ms/step - loss: 0.0682 - accuracy: 0.9789


In [14]:
print(test_loss)
print(test_acc)

0.06816446781158447
0.9789000153541565
