In [1]:
import numpy as np
x=np.array(12)
print(x)
print(x.ndim)

12
0


In [2]:
x=np.array([1,2,3,6,14])
x
print(x.ndim)

1


In [3]:
x=np.array([[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]])
print(x)
print(x.ndim)
print(x.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
2
(3, 5)


In [4]:
x=np.array([[[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]],
           [[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]]])
print(x)
print(x.ndim)
print(x.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
3
(2, 3, 5)


In [5]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()
digit=train_images[0]
import matplotlib.pyplot as plt
plt.imshow(digit,cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

In [6]:
my_slice=train_images[10:100]
#print(my_slice)
print(my_slice.shape)
my_slice=train_images[10:100,:,:]
print(my_slice.shape)
print(train_images.ndim)
print(train_images.shape)
my_slice=train_images[10:100,0:28,0:28]
print(my_slice.shape)

(90, 28, 28)
(90, 28, 28)
3
(60000, 28, 28)
(90, 28, 28)


In [7]:
my_slice=train_images[:,14:,14:]
print(my_slice.shape)
my_slice=train_images[:,7:-7,7:-7]
print(my_slice.shape)

(60000, 14, 14)
(60000, 14, 14)


In [9]:
x=np.array([1,3])
y=np.array([2,4])

def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0],"shape mismatch"
    z=0
    for i in range(x.shape[0]):
        z+=x[i]*y[i]
    return z

print(naive_vector_dot(x,y))

14


In [10]:
x=np.array([[1,3],[-1,4]])
y=np.array([2,4])
print(x.shape)
print(y.shape)

def naive_add_matrix_add_vector(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    
    for i in range(x.shape[0]):
        for j in range (x.shape[0]):
            x[i][j]+=y[j]
    return x
print(naive_add_matrix_add_vector(x,y))

(2, 2)
(2,)
[[3 7]
 [1 8]]


In [11]:
x=np.array([1,3])
y=np.array([2,4])

def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0],"shape mismatch"
    z=0
    
    for i in range (x.shape[0]):
        z+=x[i]*y[i]
    return z
print(naive_vector_dot(x,y))


14


In [12]:
x=np.array([[1,3],[-1,4],[-1,4]])
y=np.array([2,4])
def naive_matrix_vector_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    
    z=np.zeros(x.shape[0])
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i]=x[i][j]*y[j]
    return z
print(naive_matrix_vector_dot(x,y))

[12. 16. 16.]


In [16]:
x=np.array([[1,3,4],[2,4,6]])
y=np.array([[2,4],[3,5],[7,2]])
#print(x)
#print(y)

In [17]:
def naive_matrix_dot(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==2
    assert x.shape[1]==y.shape[0]
    z=np.zeros((x.shape[0],y.shape[0]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x=x[i,:]
            column_y=y[:,j]
            z[i,j]=naive_vector_dot(row_x,column_y)
    return z
print(naive_matrix_dot(x,y))


[[39. 27.  0.]
 [58. 40.  0.]]


In [22]:
x=np.array([[0,1],[2,3],[4,6]])
print(x)
print(x.shape)
x=x.reshape((6,1))
#print(x)
x=x.reshape((2,3))
#print(x)

[[0 1]
 [2 3]
 [4 6]]
(3, 2)


In [24]:
x=np.zeros((30,10))
print(x)
x=np.transpose(x)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0